#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import {
  AuthorityError,
  authorityFromValidatedFixture,
  authorizeCampaignOpening,
  computeAuthorizedUseDigest,
  evaluateAuthorizedUse,
  signFixtureEnvelope,
  verifyEnvelope,
} from "./validate_guided_autonomy_authority.mjs";

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const LAB=path.join(ROOT,"conformance","recursive_improvement_lab_vectors.json");
const AUTH=path.join(ROOT,"conformance","guided_autonomy_vectors.json");
const FORBIDDEN=["active_writer.assign","authority.self_grant","guardian.replace","identity.modify","main.protection.disable","memory.rewrite","private_eval.read"];
function canonical(x){if(Array.isArray(x))return x.map(canonical);if(x&&typeof x==="object")return Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])]));return x}
const h=(d,o)=>`sha256:${crypto.createHash("sha256").update(`${d}\n${JSON.stringify(canonical(o))}`).digest("hex")}`;
const plus=(ts,seconds)=>new Date(new Date(ts).getTime()+seconds*1000).toISOString().replace(".000Z","Z");
function validateLab(input){
 const doc=structuredClone(input),c=doc.campaign,cd=c.campaign_digest;delete c.campaign_digest;if(h("campaign",c)!==cd)throw Error("campaign_digest_mismatch");c.campaign_digest=cd;if(JSON.stringify(c.forbidden_capabilities)!==JSON.stringify(FORBIDDEN)||!c.guardian_grant_ref)throw Error("authority_invalid");
 const by=new Map(),accepted=[],rejected=[],buggy=[];for(const n of doc.candidates){if(by.has(n.candidate_id))throw Error("duplicate_candidate");const d=n.candidate_digest;delete n.candidate_digest;if(h("candidate",n)!==d)throw Error("candidate_digest_mismatch");n.candidate_digest=d;const p=n.parent_candidate_ref,op=n.operator;if(!["draft","debug","improve"].includes(op))throw Error("operator_invalid");if(op==="draft"&&(p!==null||n.source_candidate_ref!==null))throw Error("draft_parent");if(op!=="draft"&&(!by.has(p)||n.source_candidate_ref!==p))throw Error("parent_missing");if(op==="debug"&&!by.get(p).execution.buggy)throw Error("debug_parent");if(op==="improve"&&by.get(p).execution.buggy)throw Error("improve_parent");const e=n.execution,v=n.evaluation,b=c.budget;let s="accepted";if(e.buggy)s="buggy";else if(e.cpu_seconds>b.max_cpu_seconds||e.memory_mb>b.max_memory_mb||e.output_bytes>b.max_output_bytes)s="rejected_budget";else if(!v.private_receipt_digest)s="rejected_private_receipt";else if(v.reward_hacking_detected)s="rejected_reward_hacking";else if(v.safety_regression_detected)s="rejected_safety";else if(!v.maintainability_passed)s="rejected_maintainability";else if(!Number.isInteger(v.public_metric_milli))s="rejected_metric";if(s!==n.expected_status)throw Error("status_mismatch");by.set(n.candidate_id,n);(s==="buggy"?buggy:s==="accepted"?accepted:rejected).push(n.candidate_id)}
 const p=doc.expected_projection,pd=p.projection_digest;delete p.projection_digest;const best=accepted.reduce((a,b)=>by.get(a).evaluation.public_metric_milli>=by.get(b).evaluation.public_metric_milli?a:b);const calc={campaign_ref:c.campaign_id,candidate_count:by.size,accepted,rejected,buggy,best_candidate_ref:best,best_metric_milli:by.get(best).evaluation.public_metric_milli};if(JSON.stringify(calc)!==JSON.stringify(p)||h("projection",p)!==pd)throw Error("projection_mismatch");if(doc.negative_case_ids.length!==20||new Set(doc.negative_case_ids).size!==20)throw Error("negative_cases");return{campaign:c,projection:{...p,projection_digest:pd},best};
}
function expectReason(label,expected,fn){const r=fn(),actual=r.decision_reason??r.reason;if(actual!==expected)throw Error(`${label}:expected:${expected}:got:${actual}`)}
function expectFailure(label,fn){try{fn()}catch(e){if(e instanceof AuthorityError)return;throw e}throw Error(`${label}:accepted`)}
function validateAuthority(lab,guided){
 const authority=authorityFromValidatedFixture(guided),grant=guided.grants.find(g=>g.capability==="code.execute_sandbox");if(!grant)throw Error("sandbox_grant_missing");const body=grant.body_ids[0],issued=guided.ledger_events.find(e=>e.grant_ref===grant.grant_id&&e.event_type==="grant.issued");if(!issued)throw Error("sandbox_grant_not_issued");const opened=plus(issued.recorded_at,1);
 const campaignSig=signFixtureEnvelope(guided.keys.guardian,"guardian",guided.guardian_id,lab.campaign.campaign_digest,"genesis.improvement.campaign.signature.v0.1",opened);verifyEnvelope(campaignSig,guided.keys.guardian,{digest:lab.campaign.campaign_digest,domain:"genesis.improvement.campaign.signature.v0.1",signerType:"guardian",signerId:guided.guardian_id,createdAt:opened,prefix:"campaign"});
 const request={campaign_digest:lab.campaign.campaign_digest,grant_ref:grant.grant_id,instance_id:guided.instance_id,body_id:body,capability:"code.execute_sandbox",target_ref:"workspace.source",action_class:"compile",data_class:"private_local",requested_actions:1,requested_duration_seconds:Math.min(lab.campaign.budget.max_cpu_seconds,grant.budget.max_duration_seconds),requested_bytes:Math.min(lab.campaign.budget.max_output_bytes,grant.budget.max_bytes_per_run),sandboxed:true,human_confirmation_ref:"confirm_01HRILAB_OPEN001",observer_ref:"observer_01HRILAB_OPEN001",reversible_plan_ref:"revert_01HRILAB_OPEN001",authorized_at:opened};
 const receipt=authorizeCampaignOpening(request,authority);if(receipt.decision_status!=="allowed"||receipt.grant_ref!==grant.grant_id)throw Error("campaign_authorization_failed");
 const use={schema_version:"genesis.autonomy.capability.use.v0.2",hash_profile:"genesis.hash.fields.v0.1",use_id:"use_01HRILAB_COMPILE001",grant_ref:grant.grant_id,instance_id:guided.instance_id,body_id:body,capability:"code.execute_sandbox",target_ref:"workspace.source",action_class:"compile",data_class:"private_local",requested_actions:1,requested_duration_seconds:30,requested_bytes:1000000,sandboxed:true,human_confirmation_ref:"confirm_01HRILAB_USE001",observer_ref:"observer_01HRILAB_USE001",reversible_plan_ref:"revert_01HRILAB_USE001",requested_at:plus(opened,1),use_digest:"",signature:null};use.use_digest=computeAuthorizedUseDigest(use);use.signature=signFixtureEnvelope(guided.keys.body,"body",body,use.use_digest,"genesis.autonomy.capability.use.signature.v0.2",use.requested_at);const decision=evaluateAuthorizedUse(use,authority);if(decision.status!=="allowed")throw Error(`authorized_use_failed:${decision.reason}`);
 let negatives=0;expectReason("synthetic","grant_missing",()=>authorizeCampaignOpening({...request,grant_ref:"grant_code_sandbox_001"},authority));negatives++;expectReason("instance","grant_instance_mismatch",()=>authorizeCampaignOpening({...request,instance_id:"inst_wrong"},authority));negatives++;expectReason("early","grant_not_yet_valid",()=>authorizeCampaignOpening({...request,authorized_at:plus(grant.not_before,-1)},authority));negatives++;expectReason("bytes","byte_budget_exceeded",()=>authorizeCampaignOpening({...request,requested_bytes:grant.budget.max_bytes_per_run+1},authority));negatives++;
 const badSig=structuredClone(campaignSig);badSig.signature_value="0".repeat(128);expectFailure("campaign_signature",()=>verifyEnvelope(badSig,guided.keys.guardian,{digest:lab.campaign.campaign_digest,domain:"genesis.improvement.campaign.signature.v0.1",signerType:"guardian",signerId:guided.guardian_id,createdAt:opened,prefix:"campaign"}));negatives++;const badUse=structuredClone(use);badUse.grant_ref="grant_other";expectFailure("signed_grant_ref",()=>evaluateAuthorizedUse(badUse,authority));negatives++;
 for(const [eventType,reason] of [["grant.suspended","grant_suspended"],["grant.revoked","grant_revoked"]]){const event=guided.ledger_events.find(e=>e.grant_ref===grant.grant_id&&e.event_type===eventType);if(!event)throw Error(`${eventType}_fixture_missing`);expectReason(eventType,reason,()=>authorizeCampaignOpening({...request,authorized_at:event.recorded_at},authority));negatives++}
 return{receipt,decision,negatives};
}
function main(){const lab=validateLab(JSON.parse(fs.readFileSync(path.resolve(process.argv[2]??LAB),"utf8"))),integration=validateAuthority(lab,JSON.parse(fs.readFileSync(path.resolve(process.argv[3]??AUTH),"utf8")));console.log(`OK recursive improvement laboratory (${lab.projection.candidate_count} candidates; best=${lab.best})`);console.log(`OK projection digest ${lab.projection.projection_digest}`);console.log(`OK signed exact-grant campaign authorization ${integration.receipt.campaign_authorization_digest}`);console.log(`OK signed v0.2 use decision ${integration.decision.decision_digest}`);console.log(`OK authority integration negative cases (${integration.negatives})`);console.log("NOTE campaign opening does not consume a use; each signed sandbox use is re-evaluated against the current ledger.")}
try{main()}catch(error){console.error(`FAIL recursive improvement laboratory: ${error.message}`);process.exit(1)}
