#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { computeEventHash } from "./guided_autonomy.mjs";
import {
  AuthorityError,
  authorityFromValidatedFixture,
  authorizeCampaignOpening,
  computeAuthorizedUseDigest,
  evaluateAuthorizedUse,
  hashAuthorityFields,
  resolveExactGrant,
  signFixtureEnvelope,
  validateAuthorityBundle,
  verifyEnvelope,
} from "./validate_guided_autonomy_authority.mjs";

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const LAB=path.join(ROOT,"conformance","recursive_improvement_lab_vectors.json");
const AUTH=path.join(ROOT,"conformance","guided_autonomy_vectors.json");
const FORBIDDEN=["active_writer.assign","authority.self_grant","guardian.replace","identity.modify","main.protection.disable","memory.rewrite","private_eval.read"];
function canonical(x){if(Array.isArray(x))return x.map(canonical);if(x&&typeof x==="object")return Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])]));return x}
const h=(d,o)=>`sha256:${crypto.createHash("sha256").update(`${d}\n${JSON.stringify(canonical(o))}`).digest("hex")}`;
const plus=(ts,seconds)=>new Date(new Date(ts).getTime()+seconds*1000).toISOString().replace(".000Z","Z");
function validateLab(input){
 const doc=structuredClone(input),c=doc.campaign,cd=c.campaign_digest;delete c.campaign_digest;if(h("campaign",c)!==cd)throw Error("campaign_digest_mismatch");c.campaign_digest=cd;if(c.schema_version!=="genesis.improvement.campaign.v0.2"||JSON.stringify(c.forbidden_capabilities)!==JSON.stringify(FORBIDDEN)||!c.guardian_grant_ref||!c.opened_at||!c.authority_binding)throw Error("authority_invalid");
 const by=new Map(),accepted=[],rejected=[],buggy=[];for(const n of doc.candidates){if(by.has(n.candidate_id))throw Error("duplicate_candidate");const d=n.candidate_digest;delete n.candidate_digest;if(h("candidate",n)!==d)throw Error("candidate_digest_mismatch");n.candidate_digest=d;const p=n.parent_candidate_ref,op=n.operator;if(!["draft","debug","improve"].includes(op))throw Error("operator_invalid");if(op==="draft"&&(p!==null||n.source_candidate_ref!==null))throw Error("draft_parent");if(op!=="draft"&&(!by.has(p)||n.source_candidate_ref!==p))throw Error("parent_missing");if(op==="debug"&&!by.get(p).execution.buggy)throw Error("debug_parent");if(op==="improve"&&by.get(p).execution.buggy)throw Error("improve_parent");const e=n.execution,v=n.evaluation,b=c.budget;let s="accepted";if(e.buggy)s="buggy";else if(e.cpu_seconds>b.max_cpu_seconds||e.memory_mb>b.max_memory_mb||e.output_bytes>b.max_output_bytes)s="rejected_budget";else if(!v.private_receipt_digest)s="rejected_private_receipt";else if(v.reward_hacking_detected)s="rejected_reward_hacking";else if(v.safety_regression_detected)s="rejected_safety";else if(!v.maintainability_passed)s="rejected_maintainability";else if(!Number.isInteger(v.public_metric_milli))s="rejected_metric";if(s!==n.expected_status)throw Error("status_mismatch");by.set(n.candidate_id,n);(s==="buggy"?buggy:s==="accepted"?accepted:rejected).push(n.candidate_id)}
 const p=doc.expected_projection,pd=p.projection_digest;delete p.projection_digest;const best=accepted.reduce((a,b)=>by.get(a).evaluation.public_metric_milli>=by.get(b).evaluation.public_metric_milli?a:b);const calc={campaign_ref:c.campaign_id,candidate_count:by.size,accepted,rejected,buggy,best_candidate_ref:best,best_metric_milli:by.get(best).evaluation.public_metric_milli};if(JSON.stringify(calc)!==JSON.stringify(p)||h("projection",p)!==pd)throw Error("projection_mismatch");if(doc.negative_case_ids.length!==20||new Set(doc.negative_case_ids).size!==20)throw Error("negative_cases");return{campaign:c,candidates:[...by.values()],projection:{...p,projection_digest:pd},best,expectedAuthority:doc.expected_authority_execution};
}
function expectReason(label,expected,fn){const r=fn(),actual=r.decision_reason??r.reason;if(actual!==expected)throw Error(`${label}:expected:${expected}:got:${actual}`)}
function expectFailure(label,fn){try{fn()}catch(e){if(e instanceof AuthorityError)return;throw e}throw Error(`${label}:accepted`)}
export function buildCandidateAuthorityExecution(lab,guided,baseAuthority,checkExpected=true){
 const grant=baseAuthority.grants.get(lab.campaign.guardian_grant_ref);if(!grant)throw Error("candidate_mapping_grant_missing");const binding=lab.campaign.authority_binding,bundle=structuredClone(baseAuthority.bundle),mapping=[];let cursor=plus(lab.campaign.opened_at,60),index=0,currentAuthority=baseAuthority;
 for(const candidate of lab.candidates){const actions=["compile",...(candidate.execution.buggy?[]:["test"])];for(const actionClass of actions){index++;const n=String(index).padStart(2,"0"),use={schema_version:"genesis.autonomy.capability.use.v0.2",hash_profile:"genesis.hash.fields.v0.1",use_id:`use_01HRILAB_${n}`,grant_ref:grant.grant_id,instance_id:lab.campaign.instance_id,body_id:binding.body_id,capability:binding.capability,target_ref:binding.target_ref,action_class:actionClass,data_class:binding.data_class,requested_actions:1,requested_duration_seconds:Math.max(1,Math.min(candidate.execution.cpu_seconds,grant.budget.max_duration_seconds)),requested_bytes:Math.min(candidate.execution.output_bytes,grant.budget.max_bytes_per_run),sandboxed:binding.sandboxed,human_confirmation_ref:`confirm_01HRILAB_${n}`,observer_ref:`observer_01HRILAB_${n}`,reversible_plan_ref:`revert_01HRILAB_${n}`,requested_at:cursor,use_digest:"",signature:null};use.use_digest=computeAuthorizedUseDigest(use);use.signature=signFixtureEnvelope(guided.keys.body,"body",binding.body_id,use.use_digest,"genesis.autonomy.capability.use.signature.v0.2",use.requested_at);bundle.use_requests.push(use);currentAuthority=validateAuthorityBundle(bundle,baseAuthority.keyResolver);const decision=evaluateAuthorizedUse(use,currentAuthority);if(decision.status!=="allowed")throw Error(`candidate_use_denied:${candidate.candidate_id}:${actionClass}:${decision.reason}`);const recordedAt=plus(cursor,1),event={schema_version:guided.domains.event,hash_profile:"genesis.hash.fields.v0.1",ledger_id:bundle.ledger_events[0].ledger_id,event_id:`capevent_01HRILAB_${n}`,sequence:bundle.ledger_events.length,previous_event_hash:bundle.ledger_events.at(-1).event_hash,guardian_id:guided.guardian_id,instance_id:guided.instance_id,authority_epoch:guided.authority_epoch,event_type:"grant.consumed",grant_ref:grant.grant_id,body_id:binding.body_id,use_id:use.use_id,subject_digest:use.use_digest,recorded_at:recordedAt,event_hash:"",signature:null};event.event_hash=computeEventHash(event);event.signature=signFixtureEnvelope(guided.keys.body,"body",binding.body_id,event.event_hash,guided.domains.event_signature,recordedAt);bundle.ledger_events.push(event);currentAuthority=validateAuthorityBundle(bundle,baseAuthority.keyResolver);mapping.push({candidate_ref:candidate.candidate_id,action_class:actionClass,use_ref:use.use_id,event_ref:event.event_id,decision_digest:decision.decision_digest});cursor=plus(cursor,2)}}
 const finalResolved=resolveExactGrant(grant.grant_id,grant.capability,grant.instance_id,cursor,currentAuthority);if(finalResolved.reason!=="grant_exhausted")throw Error(`candidate_mapping_not_exhausted:${finalResolved.reason}`);const fields=[lab.campaign.campaign_id,grant.grant_id,String(mapping.length),...mapping.flatMap(item=>[item.candidate_ref,item.action_class,item.use_ref,item.event_ref,item.decision_digest])],summary={operation_count:mapping.length,compile_count:mapping.filter(item=>item.action_class==="compile").length,test_count:mapping.filter(item=>item.action_class==="test").length,consumed_use_count:finalResolved.state.consumed.size,final_grant_status:"exhausted",mapping_digest:hashAuthorityFields("genesis.improvement.candidate.authority.mapping.v0.1",fields),final_ledger_head_hash:bundle.ledger_events.at(-1).event_hash};if(checkExpected&&JSON.stringify(summary)!==JSON.stringify(lab.expectedAuthority))throw Error("candidate_authority_mapping_mismatch");return{summary,mapping,bundle,authority:currentAuthority,firstUse:bundle.use_requests.at(-mapping.length)};
}
function validateAuthority(lab,guided){
 const authority=authorityFromValidatedFixture(guided);if(["keys","expected","must_reject"].some(field=>Object.hasOwn(authority.bundle,field)))throw Error("neutral_bundle_contains_test_fields");const grant=guided.grants.find(g=>g.grant_id===lab.campaign.guardian_grant_ref);if(!grant)throw Error("declared_grant_missing");if(lab.campaign.instance_id!==guided.instance_id||grant.instance_id!==lab.campaign.instance_id)throw Error("campaign_instance_mismatch");const binding=lab.campaign.authority_binding,issued=guided.ledger_events.find(e=>e.grant_ref===grant.grant_id&&e.event_type==="grant.issued");if(!issued)throw Error("sandbox_grant_not_issued");const opened=lab.campaign.opened_at,campaignSig=signFixtureEnvelope(guided.keys.guardian,"guardian",guided.guardian_id,lab.campaign.campaign_digest,"genesis.improvement.campaign.signature.v0.2",opened);verifyEnvelope(campaignSig,guided.keys.guardian,{digest:lab.campaign.campaign_digest,domain:"genesis.improvement.campaign.signature.v0.2",signerType:"guardian",signerId:guided.guardian_id,createdAt:opened,prefix:"campaign"});const request={campaign_digest:lab.campaign.campaign_digest,grant_ref:grant.grant_id,instance_id:lab.campaign.instance_id,...binding,authorized_at:opened},receipt=authorizeCampaignOpening(request,authority);if(receipt.decision_status!=="allowed")throw Error(`campaign_authorization_failed:${receipt.decision_reason}`);const execution=buildCandidateAuthorityExecution(lab,guided,authority,true);
 let negatives=0;expectReason("synthetic","grant_missing",()=>authorizeCampaignOpening({...request,grant_ref:"grant_code_sandbox_001"},authority));negatives++;expectReason("instance","grant_instance_mismatch",()=>authorizeCampaignOpening({...request,instance_id:"inst_wrong"},authority));negatives++;expectReason("early","grant_not_yet_valid",()=>authorizeCampaignOpening({...request,authorized_at:plus(grant.not_before,-1)},authority));negatives++;expectReason("bytes","byte_budget_exceeded",()=>authorizeCampaignOpening({...request,requested_bytes:grant.budget.max_bytes_per_run+1},authority));negatives++;const badSig=structuredClone(campaignSig);badSig.signature_value="0".repeat(128);expectFailure("campaign_signature",()=>verifyEnvelope(badSig,guided.keys.guardian,{digest:lab.campaign.campaign_digest,domain:"genesis.improvement.campaign.signature.v0.2",signerType:"guardian",signerId:guided.guardian_id,createdAt:opened,prefix:"campaign"}));negatives++;const badUse=structuredClone(execution.firstUse);badUse.grant_ref="grant_other";expectFailure("signed_grant_ref",()=>evaluateAuthorizedUse(badUse,authority));negatives++;
 const controlGrant=guided.grants.find(item=>item.grant_id==="grant_01HAUTONOMY_CODE000001");for(const [eventType,reason] of [["grant.suspended","grant_suspended"],["grant.revoked","grant_revoked"]]){const event=guided.ledger_events.find(e=>e.grant_ref===controlGrant.grant_id&&e.event_type===eventType);expectReason(eventType,reason,()=>authorizeCampaignOpening({...request,grant_ref:controlGrant.grant_id,authorized_at:event.recorded_at},authority));negatives++}
 const broken=structuredClone(authority.bundle);broken.ledger_events[1].previous_event_hash="sha256:"+"0".repeat(64);expectFailure("neutral_bundle_ledger",()=>validateAuthorityBundle(broken,authority.keyResolver));negatives++;const wrongEvent=structuredClone(execution.bundle);wrongEvent.ledger_events.at(-1).grant_ref="grant_other";expectFailure("candidate_consumption_grant",()=>validateAuthorityBundle(wrongEvent,authority.keyResolver));negatives++;const shortened=structuredClone(execution.bundle);shortened.ledger_events.pop();const shortenedAuthority=validateAuthorityBundle(shortened,authority.keyResolver),shortenedState=resolveExactGrant(grant.grant_id,grant.capability,grant.instance_id,plus(shortened.ledger_events.at(-1).recorded_at,1),shortenedAuthority);if(shortenedState.reason==="grant_exhausted")throw Error("candidate_mapping_missing_event_accepted");negatives++;return{receipt,execution,negatives};
}
function main(){const lab=validateLab(JSON.parse(fs.readFileSync(path.resolve(process.argv[2]??LAB),"utf8"))),integration=validateAuthority(lab,JSON.parse(fs.readFileSync(path.resolve(process.argv[3]??AUTH),"utf8")));console.log(`OK recursive improvement laboratory (${lab.projection.candidate_count} candidates; best=${lab.best})`);console.log(`OK projection digest ${lab.projection.projection_digest}`);console.log(`OK signed exact-grant campaign authorization ${integration.receipt.campaign_authorization_digest}`);console.log(`OK candidate authority mapping (${integration.execution.summary.operation_count} signed uses; ${integration.execution.summary.final_grant_status})`);console.log(`OK candidate authority mapping digest ${integration.execution.summary.mapping_digest}`);console.log(`OK authority integration negative cases (${integration.negatives})`)}
try{main()}catch(error){console.error(`FAIL recursive improvement laboratory: ${error.message}`);process.exit(1)}
