#!/usr/bin/env node
import crypto from"node:crypto";import fs from"node:fs";import path from"node:path";import{fileURLToPath}from"node:url";
const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url))),input=process.argv[2]??path.join(ROOT,"conformance","operational_deliberation_proof_vectors.json");
const CONST=new Set(["active_writer.assign","authority.self_grant","guardian.replace","identity.modify","main.protection.disable","memory.rewrite","private_eval.read","third_party_rights.override"]);
const TRANS=new Set(["received>classified","classified>evidence","evidence>decision","decision>execute","decision>verify","decision>blocked","execute>verify","verify>verified","verify>refuted","verify>awaiting_authorization","blocked>verify","verified>reported","refuted>reported","awaiting_authorization>reported"]);
const a=(c,m)=>{if(!c)throw Error(m)},can=x=>Array.isArray(x)?x.map(can):x&&typeof x==="object"?Object.fromEntries(Object.keys(x).sort().map(k=>[k,can(x[k])])):x,st=x=>JSON.stringify(can(x)),h=(d,x)=>"sha256:"+crypto.createHash("sha256").update(d+"\n"+st(x)).digest("hex");
function dg(o,f,d){const v=o[f];delete o[f];a(h(d,o)===v,f+"_mismatch");o[f]=v}
function fr(t){const f=new Set;if(t.changed.some(x=>!t.scope.includes(x)))f.add("scope_creep");if(!t.claims_observed)f.add("false_completion");if(t.changed.length&&(!t.done||!t.surrounding))f.add("verification_theater");if(t.defect&&!t.twin)f.add("missed_twins");if(t.outward&&!t.grant)f.add("unauthorized_external_action");return[...f].sort()}
function vt(t,p){dg(t,"digest","task");a(p.shapes.includes(t.shape),"shape");a(t.evidence>0&&t.checks>0,"done");a(Number.isInteger(t.cycles)&&t.cycles<=3,"retry");if(t.shape==="assessment")a(!t.changed.length&&!t.outward,"assessment");if(t.changed.length)a(t.intent!=="none","intent");a(t.intent!=="conflict","conflict");if(t.verdict!=="REFUTED")a(t.changed.every(x=>t.scope.includes(x)),"scope");if(t.outward)a(Boolean(t.grant),"grant");if(t.pending)a(!t.outward&&!t.grant,"pending");const r=t.rule;if(r){if(["advisory","procedural"].includes(r.class))a(r.decision==="local_exception"&&r.reversible&&r.bounded&&!r.outward&&r.grant===null,"local_exception");else if(r.class==="capability")a(r.decision==="guardian_exception"&&r.grant,"capability");else if(r.class==="constitutional")a(r.decision==="denied"&&CONST.has(r.rule_id),"constitutional");else throw Error("rule")}a(t.states[0]==="received"&&t.states.at(-1)==="reported","states");for(let i=0;i<t.states.length-1;i++)a(TRANS.has(t.states[i]+">"+t.states[i+1]),"transition");const f=fr(t);a(st(f)===st([...t.frauds].sort()),"frauds");const e=f.length?"REFUTED":t.pending?"VERIFIED_WITH_CAVEATS":"VERIFIED";a(t.verdict===e,"verdict");if(e==="VERIFIED")a(t.done&&t.surrounding,"verified");return e}
const d=JSON.parse(fs.readFileSync(input,"utf8")),p=d.profile;dg(p,"digest","profile");a(p.source_repo==="Sahir619/fable-method"&&p.source_commit==="88b5cf36b10ee3679e08ee0f0181b9774d481508"&&p.source_license==="MIT","source");a(st([...p.constitutional].sort())===st([...CONST].sort()),"constitutional_set");a(st(p.runtime)===st({platform:"android",repo:"morimilpabfelon-cell/Morimil-app",precondition:"cleanup_and_audit"}),"runtime");
const ids=new Set;for(const x of d.domains){dg(x,"digest","domain");a(!ids.has(x.id),"duplicate_domain");ids.add(x.id);a(x.minimum_evidence>=3&&x.authority_levels>=4&&x.verification_checks>=3&&x.fraud_signals>=5,"domain")}a(ids.has("android_runtime")&&ids.size===10,"domains");a(d.failure_modes.length===18&&new Set(d.failure_modes).size===18,"failures");a(d.traps.length===10&&d.traps.every(x=>["VERIFIED","VERIFIED_WITH_CAVEATS","REFUTED"].includes(x[1])),"traps");
const tids=new Set,vc={};let le=0,cd=0;for(const t of d.tasks){a(!tids.has(t.id),"duplicate_task");tids.add(t.id);const v=vt(t,p);vc[v]=(vc[v]??0)+1;if(t.rule?.decision==="local_exception")le++;if(t.rule?.decision==="denied")cd++}
const pr=d.projection,pd=pr.digest;delete pr.digest;const calc={domains:d.domains.length,failures:d.failure_modes.length,traps:d.traps.length,tasks:d.tasks.length,verdicts:vc,local_exceptions:le,constitutional_denials:cd,android_first:p.runtime.platform==="android"};a(st(calc)===st(pr)&&h("projection",pr)===pd,"projection");pr.digest=pd;a(d.negative_cases.length===40&&new Set(d.negative_cases).size===40,"negative");
console.log(`OK operational deliberation and proof (${pr.tasks} tasks; ${pr.domains} domains; ${pr.traps} traps)`);console.log(`OK projection digest ${pr.digest}`);console.log("OK bounded rule exceptions; constitutional boundaries remain non-overridable");console.log("NOTE Android is the first runtime target after Morimil-app cleanup and audit.");
