#!/usr/bin/env node
import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';
const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url)));const input=process.argv[2]??path.join(ROOT,'conformance','recursive_improvement_lab_vectors.json');
function canonical(x){if(Array.isArray(x))return x.map(canonical);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])]));return x}
const h=(d,o)=>'sha256:'+crypto.createHash('sha256').update(d+'\n'+JSON.stringify(canonical(o))).digest('hex');
const doc=JSON.parse(fs.readFileSync(input,'utf8'));const c=doc.campaign;const cd=c.campaign_digest;delete c.campaign_digest;if(h('campaign',c)!==cd)throw Error('campaign_digest_mismatch');c.campaign_digest=cd;
const forbidden=['active_writer.assign','authority.self_grant','guardian.replace','identity.modify','main.protection.disable','memory.rewrite','private_eval.read'];if(JSON.stringify(c.forbidden_capabilities)!==JSON.stringify(forbidden)||!c.guardian_grant_ref)throw Error('authority_invalid');
const by=new Map(),accepted=[],rejected=[],buggy=[];for(const n of doc.candidates){if(by.has(n.candidate_id))throw Error('duplicate_candidate');const d=n.candidate_digest;delete n.candidate_digest;if(h('candidate',n)!==d)throw Error('candidate_digest_mismatch');n.candidate_digest=d;const p=n.parent_candidate_ref;if(!['draft','debug','improve'].includes(n.operator))throw Error('operator_invalid');if(n.operator==='draft'&&(p!==null||n.source_candidate_ref!==null))throw Error('draft_parent');if(n.operator!=='draft'&&(!by.has(p)||n.source_candidate_ref!==p))throw Error('parent_missing');if(n.operator==='debug'&&!by.get(p).execution.buggy)throw Error('debug_parent');if(n.operator==='improve'&&by.get(p).execution.buggy)throw Error('improve_parent');const e=n.execution,v=n.evaluation,b=c.budget;let s='accepted';if(e.buggy)s='buggy';else if(e.cpu_seconds>b.max_cpu_seconds||e.memory_mb>b.max_memory_mb||e.output_bytes>b.max_output_bytes)s='rejected_budget';else if(!v.private_receipt_digest)s='rejected_private_receipt';else if(v.reward_hacking_detected)s='rejected_reward_hacking';else if(v.safety_regression_detected)s='rejected_safety';else if(!v.maintainability_passed)s='rejected_maintainability';else if(!Number.isInteger(v.public_metric_milli))s='rejected_metric';if(s!==n.expected_status)throw Error('status_mismatch');by.set(n.candidate_id,n);(s==='buggy'?buggy:s==='accepted'?accepted:rejected).push(n.candidate_id)}
const p=doc.expected_projection,pd=p.projection_digest;delete p.projection_digest;const best=accepted.reduce((a,b)=>by.get(a).evaluation.public_metric_milli>=by.get(b).evaluation.public_metric_milli?a:b);const calc={campaign_ref:c.campaign_id,candidate_count:by.size,accepted,rejected,buggy,best_candidate_ref:best,best_metric_milli:by.get(best).evaluation.public_metric_milli};if(JSON.stringify(calc)!==JSON.stringify(p)||h('projection',p)!==pd)throw Error('projection_mismatch');if(doc.negative_case_ids.length!==20||new Set(doc.negative_case_ids).size!==20)throw Error('negative_cases');console.log(`OK recursive improvement laboratory (${by.size} candidates; best=${best})`);console.log(`OK projection digest ${pd}`);console.log('OK 20 boundary rejection categories declared');console.log('NOTE candidates never self-authorize or merge to main.');
